export const TASK_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  PENDING_ASSIGN: 'PENDING_ASSIGN',
  PENDING_START: 'PENDING_START',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING_ACCEPT: 'PENDING_ACCEPT',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
}

export const STATUS_TEXT = {
  [TASK_STATUS.DRAFT]: '草稿',
  [TASK_STATUS.PUBLISHED]: '已发布',
  [TASK_STATUS.PENDING_ASSIGN]: '待分配',
  [TASK_STATUS.PENDING_START]: '待开始',
  [TASK_STATUS.IN_PROGRESS]: '进行中',
  [TASK_STATUS.PENDING_ACCEPT]: '待验收',
  [TASK_STATUS.REJECTED]: '已驳回',
  [TASK_STATUS.COMPLETED]: '已完成'
}

export const STATUS_COLOR = {
  [TASK_STATUS.DRAFT]: '#909399',
  [TASK_STATUS.PUBLISHED]: '#409EFF',
  [TASK_STATUS.PENDING_ASSIGN]: '#E6A23C',
  [TASK_STATUS.PENDING_START]: '#E6A23C',
  [TASK_STATUS.IN_PROGRESS]: '#67C23A',
  [TASK_STATUS.PENDING_ACCEPT]: '#409EFF',
  [TASK_STATUS.REJECTED]: '#F56C6C',
  [TASK_STATUS.COMPLETED]: '#67C23A'
}

export const PRIORITY_TEXT = {
  HIGH: '高',
  MEDIUM: '中',
  LOW: '低'
}

export const PRIORITY_COLOR = {
  HIGH: '#F56C6C',
  MEDIUM: '#E6A23C',
  LOW: '#67C23A'
}
